### ISSUE TITLE
dataset download

### ISSUE THREAD

**Issue by natlank** [cnuzh/LG-GNN#2]
Do you know how to download the dataset for this article, and may I ask what the derivative of the python command is when downloading abide? Thank you

**Comment by cnuzh** [comment]
@natlank The link to download the data has been given in the original article, and the corresponding websites have detailed instructions.

**Comment by natlank** [comment]
<img width="850" alt="截屏2023-11-21 上午" src="https://github.com/cnuzh/LG-GNN/assets/144540736/92b3a415-1ae2-49f8-a757-f1114a486344">
abide数据下载下来是这样的吗？参数是CPAC, filt_noglobal, rois_ho，一共111个不同脑区，完整的数据就这些吧

**Comment by sws827767542** [comment]
> <img alt="截屏2023-11-21 上午" width="850" src="https://private-user-images.githubusercontent.com/144540736/284492521-92b3a415-1ae2-49f8-a757-f1114a486344.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNzE0MDgsIm5iZiI6MTcwNjE3MTEwOCwicGF0aCI6Ii8xNDQ1NDA3MzYvMjg0NDkyNTIxLTkyYjNhNDE1LTFhZTItNDlmOC1hNzU3LWYxMTE0YTQ4NjM0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEyNVQwODI1MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04M2I3ODcxMDQ2NGNmODc5MzcyNTIyZjUyNzBiZTAyY2VjMGEzMGVhY2JkNzlhZWFmMGEwOGExMDlhNDQ4Mjc0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.n0MxB7-fIIlvSWvVaxGdwk8qitMmzBX8p56aJPrX7Nk"> abide数据下载下来是这样的吗？参数是CPAC, filt_noglobal, rois_ho，一共111个不同脑区，完整的数据就这些吧

请问您使用什么命令下载的

**Comment by sws827767542** [comment]
您好，为什么我subject_IDs = Render.get_ids()这句话报错

**Comment by natlank** [comment]
刚看到，代码我有些忘了，明天有空可以聊聊，我邮箱generalzx10@aliyun.com
